Access World's sorting ivar directly
Was getting "undefined method `show' for nil:NilClass (NoMethodError)"
in failed When step, with code "sorting.show"

Now getting "undefined method `show' for #<RecordParser::Sorting::ByGenderAndLastName:"
which is normal and expected.